export const serviceAreas = [
    { name: "Phoenix", slug: "phoenix" },
    { name: "Mesa", slug: "mesa" },
    { name: "Chandler", slug: "chandler" },
    { name: "Glendale", slug: "glendale" },
    { name: "Tempe", slug: "tempe" },
    { name: "Peoria", slug: "peoria" },
    { name: "Scottsdale", slug: "scottsdale" },
    { name: "Surprise", slug: "surprise" },
    { name: "Avondale", slug: "avondale" },
    { name: "Goodyear", slug: "goodyear" },
    { name: "Tucson", slug: "tucson" },
    { name: "Flagstaff", slug: "flagstaff" },
    { name: "Prescott", slug: "prescott" },
    { name: "Kingman", slug: "kingman" },
    { name: "Casa Grande", slug: "casa-grande" },
    { name: "Sierra Vista", slug: "sierra-vista" },
    { name: "Apache Junction", slug: "apache-junction" },
    { name: "Bullhead City", slug: "bullhead-city" },
    { name: "Lake Havasu City", slug: "lake-havasu-city" },
    { name: "Maricopa", slug: "maricopa" },
    { name: "Gilbert", slug: "gilbert" },
    { name: "Yuma", slug: "yuma" }
  ];
  